#!/usr/bin/env bash
# =============================================================================
# Refreshes /etc/nginx/conf.d/cloudflare-realip.conf from Cloudflare's
# published edge ranges.
#
#   sudo ./scripts/update-cloudflare-ips.sh
#
# Cloudflare adds ranges occasionally. A missing range means requests through
# that POP keep the edge address instead of the visitor's, and those visitors
# all land in one bucket in the sign-in throttle. Worth a monthly cron:
#   0 4 1 * *  /var/www/chunithm-queue/scripts/update-cloudflare-ips.sh
# =============================================================================

set -euo pipefail

TARGET=/etc/nginx/conf.d/cloudflare-realip.conf
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

fetch() {
  curl -fsS --max-time 20 "$1"
}

echo "Fetching Cloudflare ranges…"
V4=$(fetch https://www.cloudflare.com/ips-v4)
V6=$(fetch https://www.cloudflare.com/ips-v6)

# A truncated download would silently shrink the trusted set, and every range
# that drops off stops resolving real client IPs. Refuse anything implausible.
COUNT=$(printf '%s\n%s\n' "$V4" "$V6" | grep -c '/' || true)
if [ "$COUNT" -lt 15 ]; then
  echo "Only $COUNT ranges returned — that is too few to be real. Keeping the existing file." >&2
  exit 1
fi

{
  echo "# Generated by scripts/update-cloudflare-ips.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Do not edit by hand — rerun the script instead."
  echo
  printf '%s\n' "$V4" | sed 's/^/set_real_ip_from /; s/$/;/'
  echo
  printf '%s\n' "$V6" | sed 's/^/set_real_ip_from /; s/$/;/'
  echo
  echo "real_ip_header CF-Connecting-IP;"
} > "$TMP"

install -m 0644 "$TMP" "$TARGET"

echo "Wrote $COUNT ranges to $TARGET"
nginx -t && systemctl reload nginx
echo "nginx reloaded."
